// Mock data for Blog - Easy to replace with backend data

export const MOCK_BLOG_POSTS = [
  {
    id: "1",
    title: "Getting Started with React Hooks: A Comprehensive Guide",
    slug: "getting-started-react-hooks",
    excerpt: "Learn how to use React Hooks to manage state and side effects in your functional components with this in-depth guide.",
    content: "Full content here...",
    featuredImage: "https://images.unsplash.com/photo-1633356122544-f134324ef6db?auto=format&fit=crop&w=1920&q=80",
    author: "Jane Developer",
    publishedAt: "2024-01-15",
    category: "Development",
    readTime: 8,
    tags: ["React", "JavaScript", "Hooks"],
  },
  {
    id: "2",
    title: "The Future of Web Design: Trends to Watch in 2024",
    slug: "future-web-design-2024",
    excerpt: "Explore the latest web design trends that are shaping the digital landscape and how to implement them in your projects.",
    content: "Full content here...",
    featuredImage: "https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=1920&q=80",
    author: "Alex Chen",
    publishedAt: "2024-01-10",
    category: "Design",
    readTime: 6,
    tags: ["Design", "Trends", "Web"],
  },
  {
    id: "3",
    title: "Mastering TypeScript: Advanced Patterns and Best Practices",
    slug: "mastering-typescript",
    excerpt: "Discover advanced TypeScript patterns and best practices that will elevate your code quality and developer experience.",
    content: "Full content here...",
    featuredImage: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=1920&q=80",
    author: "Mike Johnson",
    publishedAt: "2024-01-08",
    category: "Development",
    readTime: 12,
    tags: ["TypeScript", "Programming", "Best Practices"],
  },
  {
    id: "4",
    title: "E-commerce Best Practices: Converting Visitors to Customers",
    slug: "ecommerce-best-practices",
    excerpt: "Learn proven strategies and techniques to optimize your e-commerce store and increase conversion rates.",
    content: "Full content here...",
    featuredImage: "https://images.unsplash.com/photo-1556656793-08538906a9f8?auto=format&fit=crop&w=1920&q=80",
    author: "Sarah Mitchell",
    publishedAt: "2024-01-05",
    category: "Business",
    readTime: 10,
    tags: ["E-commerce", "Marketing", "Conversion"],
  },
  {
    id: "5",
    title: "Performance Optimization: Making Your Site Lightning Fast",
    slug: "performance-optimization",
    excerpt: "Learn techniques to optimize your website performance and improve user experience with faster load times.",
    content: "Full content here...",
    featuredImage: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1920&q=80",
    author: "Tom Williams",
    publishedAt: "2024-01-01",
    category: "Development",
    readTime: 9,
    tags: ["Performance", "Optimization", "Speed"],
  },
]

export const MOCK_CATEGORIES = [
  {
    id: "1",
    name: "Development",
    slug: "development",
    count: 12,
  },
  {
    id: "2",
    name: "Design",
    slug: "design",
    count: 8,
  },
  {
    id: "3",
    name: "Business",
    slug: "business",
    count: 6,
  },
  {
    id: "4",
    name: "Marketing",
    slug: "marketing",
    count: 5,
  },
  {
    id: "5",
    name: "Technology",
    slug: "technology",
    count: 10,
  },
]

export const MOCK_RECENT_POSTS = [
  {
    id: "1",
    title: "Getting Started with React Hooks",
    slug: "getting-started-react-hooks",
    featuredImage: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=400&q=80",
    publishedAt: "2024-01-15",
    readTime: 8,
  },
  {
    id: "2",
    title: "The Future of Web Design",
    slug: "future-web-design-2024",
    featuredImage: "https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=400&q=80",
    publishedAt: "2024-01-10",
    readTime: 6,
  },
  {
    id: "3",
    title: "Mastering TypeScript Patterns",
    slug: "mastering-typescript",
    featuredImage: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=400&q=80",
    publishedAt: "2024-01-08",
    readTime: 12,
  },
]

export const MOCK_TRENDING_POSTS = [
  {
    id: "4",
    title: "E-commerce Best Practices",
    slug: "ecommerce-best-practices",
    featuredImage: "https://images.unsplash.com/photo-1556656793-08538906a9f8?auto=format&fit=crop&w=400&q=80",
    publishedAt: "2024-01-05",
    readTime: 10,
  },
  {
    id: "5",
    title: "Performance Optimization Guide",
    slug: "performance-optimization",
    featuredImage: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=400&q=80",
    publishedAt: "2024-01-01",
    readTime: 9,
  },
  {
    id: "3",
    title: "Advanced JavaScript Techniques",
    slug: "advanced-javascript",
    featuredImage: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=400&q=80",
    publishedAt: "2023-12-28",
    readTime: 11,
  },
]